### ISSUE TITLE
CSS for fixing Safari transition effect

### ISSUE THREAD

**Issue by itsrubberduck** [lusaxweb/vuesax-next#264]
When hovering over a card or an avatar in safari, during the transition the border radius snaps to 0 and then goes back to 20px.
These lines fix this bug:
``` css
.vs-card__img, .vs-card__img img {
    transform: translate3d(0, 0, 0);
}
.vs-avatar-content:hover img {
    /* transform: scale(1.1); */
    transform: scale(1.1) translate3d(0, 0, 0);
}
```
