### ISSUE TITLE
Dark mode support?

### ISSUE THREAD

**Issue by samzhangjy** [lusaxweb/vuesax-next#44]
Hi, I saw that in the vuesax website, there is a dark mode option, but when I look into the docs, it did not mention how to enable dark mode in vuesax. Is there a way to enable it or is this a work in progress? Thanks!

**Comment by prashant1k99** [comment]
I think we can do it by accessing `this.$vs.theme = 'dark'` as it does provides the dark theme as you can find it here:
https://github.com/lusaxweb/vuesax-next/blob/master/packages/vuesax/src/styles/_dark.sass

Otherwise try doing it like this:
```js
$(".button").on("click", function(){
    // If the switch is checked switch to dark layout
    if(!$("body").hasClass(".dark-layout")){
        $("body").addClass(".dark-layout")
    }
    else{
        $("body").removeClass(".dark-layout")
    }
})
```

**Comment by samzhangjy** [comment]
@prashant1k99 I've tried it out, it still didn't work.

**Comment by samzhangjy** [comment]
I figured it out. Vuesax actually changed the theme when using `this.$vs.theme = 'dark'`, but background color and text color didn't change in body. To fix this, I need to add the following code to set it (insert it right below
```css
[vs-theme=dark] {
  --vs-background: 30, 32, 35;
  --vs-text: 255, 255, 255;
  --vs-gray-1: 24, 25, 28;
  --vs-gray-2: 20, 20, 23;
  --vs-gray-3: 15, 16, 19;
  --vs-gray-4: 10, 11, 14;
  --vs-shadow-opacity: .3;
  --vs-dark: 0, 0, 0;
  --vs-background-opacity: .6;
}
```
):
```css
[vs-theme=dark] {
  background-color: rgba(var(--vs-background), 1);
  color: rgba(var(--vs-text), 1);
}
```
